### ISSUE TITLE
the checkbox not display in role update or create

### ISSUE THREAD

**Issue by loveyuxiao** [GrapheneICT/nova-permissions#10]
the checkbox not display in role update or create

**Comment by jstojiljkovic** [comment]
Are you sure about that?
I just did a fresh install and everything seems to work

![fresh1](https://user-images.githubusercontent.com/22980168/87037943-5377ee00-c1ed-11ea-9336-012359b50423.PNG)
![fresh2](https://user-images.githubusercontent.com/22980168/87037947-5541b180-c1ed-11ea-9dba-e50353364f3b.PNG)

Did you set up everything properly?

**Comment by jstojiljkovic** [comment]
Closing this, due to not following the configuration guide, if you get the same error please attach screens with the error.

**Comment by milewski** [comment]
@jstojiljkovic Hey I have the same issue.. this is the error i get in console

![image](https://user-images.githubusercontent.com/2874967/87747872-05836b80-c827-11ea-8b2f-843bd75917d7.png)

and this is what i see:

![image](https://user-images.githubusercontent.com/2874967/87747895-0fa56a00-c827-11ea-835d-a2796424bcfa.png)

I have copied the content from your config/permission.php . they are indentical
